// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnsxhmbxvfoowcydinmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuc3hobWJ4dmZvb3djeWRpbm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjM5NDQsImV4cCI6MjA2NjY5OTk0NH0.rKMGYusTONKO5Ek2WBITmWcgXcO9Nzrole5Vu8biXtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);